version: "3.3"
services:
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - 5400:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  storage:
  postgres:
  pgadmin:
